todays date 23 Nov 2024....
this line of code is developed by MSS...
todays date is 1 june 2024
this line of code added by mss
I am in master branch....
Hello....I am in dev branch....
This is deploy.sh file

updating some deployment script...

this line is developted by KSP
